version: "3"


services:
  rootNode:
    image: test2:latest
    stdin_open: true
    tty: true
    deploy:
      restart_policy:
        condition: on-failure
    ports:
      - "5000:5000"
    networks:
      kademlia_network:
        ipv4_address: 10.0.0.3
  kademliaNodes:
    image: test:latest
    stdin_open: true
    tty: true
    deploy:
      replicas: 2
#        resources:
#           limits:
#              cpus: "0.1"
#              memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "5001:5000"
    networks:
      - kademlia_network

networks:
  kademlia_network:
    external:
      name: kademlia-network
