version: "3"

services:
  rootNode:
    depends_on:
      - "networks"
    image: test2:latest
    stdin_open: true
    tty: true
    deploy:
      restart_policy:
        condition: on-failure
    ports:
      - "5000:5000"
    networks:
      - kademlia_network
  kademliaNodes:
    depends_on:
      - "networks"
    image: test:latest
    stdin_open: true
    tty: true
    deploy:
      replicas: 2
#        resources:
#           limits:
#              cpus: "0.1"
#              memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "5001:5000"
    networks:
      - kademlia_network

networks:
  kademlia_network: