version: "3"
services:
#  rootNode:
#    image: rootnode:latest
#    stdin_open: true
#      tty: true
#      deploy:
#        restart_policy:
#          condition: on-failure
#      ports:
#        - "5000:5000"
#      networks:
#        - kademlia_network
  kademliaNodes:
    image: test:latest
    stdin_open: true
    tty: true
    deploy:
      replicas: 2
#        resources:
#           limits:
#              cpus: "0.1"
#              memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "5000:5000"
    networks:
      - kademlia_network
      
networks:
  kademlia_network: