// Code generated by protoc-gen-go. DO NOT EDIT.
// source: kademlia.proto

/*
Package kademlia is a generated protocol buffer package.

It is generated from these files:
	kademlia.proto

It has these top-level messages:
	PingRequest
	PingResponse
	StoreRequest
	StoreResponse
	FindNodeRequest
	FindNodeResponse
	FindValueResponse
*/
package kademlia

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PingRequest struct {
	Sender      string `protobuf:"bytes,1,opt,name=sender" json:"sender,omitempty"`
	Destination string `protobuf:"bytes,2,opt,name=destination" json:"destination,omitempty"`
}

func (m *PingRequest) Reset()                    { *m = PingRequest{} }
func (m *PingRequest) String() string            { return proto.CompactTextString(m) }
func (*PingRequest) ProtoMessage()               {}
func (*PingRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *PingRequest) GetSender() string {
	if m != nil {
		return m.Sender
	}
	return ""
}

func (m *PingRequest) GetDestination() string {
	if m != nil {
		return m.Destination
	}
	return ""
}

type PingResponse struct {
	Response string `protobuf:"bytes,1,opt,name=response" json:"response,omitempty"`
}

func (m *PingResponse) Reset()                    { *m = PingResponse{} }
func (m *PingResponse) String() string            { return proto.CompactTextString(m) }
func (*PingResponse) ProtoMessage()               {}
func (*PingResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *PingResponse) GetResponse() string {
	if m != nil {
		return m.Response
	}
	return ""
}

type StoreRequest struct {
	Sender string `protobuf:"bytes,1,opt,name=sender" json:"sender,omitempty"`
	Value  []byte `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (m *StoreRequest) Reset()                    { *m = StoreRequest{} }
func (m *StoreRequest) String() string            { return proto.CompactTextString(m) }
func (*StoreRequest) ProtoMessage()               {}
func (*StoreRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *StoreRequest) GetSender() string {
	if m != nil {
		return m.Sender
	}
	return ""
}

func (m *StoreRequest) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

type StoreResponse struct {
	Hash string `protobuf:"bytes,1,opt,name=hash" json:"hash,omitempty"`
}

func (m *StoreResponse) Reset()                    { *m = StoreResponse{} }
func (m *StoreResponse) String() string            { return proto.CompactTextString(m) }
func (*StoreResponse) ProtoMessage()               {}
func (*StoreResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *StoreResponse) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

type FindNodeRequest struct {
	Sender string                      `protobuf:"bytes,1,opt,name=sender" json:"sender,omitempty"`
	NodeId *FindNodeRequest_KademliaID `protobuf:"bytes,2,opt,name=nodeId" json:"nodeId,omitempty"`
}

func (m *FindNodeRequest) Reset()                    { *m = FindNodeRequest{} }
func (m *FindNodeRequest) String() string            { return proto.CompactTextString(m) }
func (*FindNodeRequest) ProtoMessage()               {}
func (*FindNodeRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *FindNodeRequest) GetSender() string {
	if m != nil {
		return m.Sender
	}
	return ""
}

func (m *FindNodeRequest) GetNodeId() *FindNodeRequest_KademliaID {
	if m != nil {
		return m.NodeId
	}
	return nil
}

type FindNodeRequest_KademliaID struct {
	KademliaID []byte `protobuf:"bytes,1,opt,name=kademliaID,proto3" json:"kademliaID,omitempty"`
}

func (m *FindNodeRequest_KademliaID) Reset()                    { *m = FindNodeRequest_KademliaID{} }
func (m *FindNodeRequest_KademliaID) String() string            { return proto.CompactTextString(m) }
func (*FindNodeRequest_KademliaID) ProtoMessage()               {}
func (*FindNodeRequest_KademliaID) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4, 0} }

func (m *FindNodeRequest_KademliaID) GetKademliaID() []byte {
	if m != nil {
		return m.KademliaID
	}
	return nil
}

type FindNodeResponse struct {
	Id       *FindNodeResponse_KademliaID `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Address  string                       `protobuf:"bytes,2,opt,name=address" json:"address,omitempty"`
	Distance *FindNodeResponse_KademliaID `protobuf:"bytes,3,opt,name=distance" json:"distance,omitempty"`
}

func (m *FindNodeResponse) Reset()                    { *m = FindNodeResponse{} }
func (m *FindNodeResponse) String() string            { return proto.CompactTextString(m) }
func (*FindNodeResponse) ProtoMessage()               {}
func (*FindNodeResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *FindNodeResponse) GetId() *FindNodeResponse_KademliaID {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *FindNodeResponse) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *FindNodeResponse) GetDistance() *FindNodeResponse_KademliaID {
	if m != nil {
		return m.Distance
	}
	return nil
}

type FindNodeResponse_KademliaID struct {
	KademliaID []byte `protobuf:"bytes,1,opt,name=kademliaID,proto3" json:"kademliaID,omitempty"`
}

func (m *FindNodeResponse_KademliaID) Reset()                    { *m = FindNodeResponse_KademliaID{} }
func (m *FindNodeResponse_KademliaID) String() string            { return proto.CompactTextString(m) }
func (*FindNodeResponse_KademliaID) ProtoMessage()               {}
func (*FindNodeResponse_KademliaID) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5, 0} }

func (m *FindNodeResponse_KademliaID) GetKademliaID() []byte {
	if m != nil {
		return m.KademliaID
	}
	return nil
}

type FindValueResponse struct {
	Value []byte `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (m *FindValueResponse) Reset()                    { *m = FindValueResponse{} }
func (m *FindValueResponse) String() string            { return proto.CompactTextString(m) }
func (*FindValueResponse) ProtoMessage()               {}
func (*FindValueResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *FindValueResponse) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

func init() {
	proto.RegisterType((*PingRequest)(nil), "PingRequest")
	proto.RegisterType((*PingResponse)(nil), "PingResponse")
	proto.RegisterType((*StoreRequest)(nil), "StoreRequest")
	proto.RegisterType((*StoreResponse)(nil), "StoreResponse")
	proto.RegisterType((*FindNodeRequest)(nil), "FindNodeRequest")
	proto.RegisterType((*FindNodeRequest_KademliaID)(nil), "FindNodeRequest.KademliaID")
	proto.RegisterType((*FindNodeResponse)(nil), "FindNodeResponse")
	proto.RegisterType((*FindNodeResponse_KademliaID)(nil), "FindNodeResponse.KademliaID")
	proto.RegisterType((*FindValueResponse)(nil), "FindValueResponse")
}

func init() { proto.RegisterFile("kademlia.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 359 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x53, 0x51, 0x4b, 0x32, 0x41,
	0x14, 0x65, 0xfd, 0xd4, 0x6f, 0x3d, 0xbb, 0x9a, 0x0e, 0x11, 0xcb, 0x16, 0x21, 0x2b, 0x44, 0x85,
	0x4c, 0xa4, 0x2f, 0x3d, 0xf4, 0x18, 0x85, 0x04, 0x11, 0x1b, 0xf4, 0xbe, 0x35, 0x43, 0x0e, 0xda,
	0x8c, 0xed, 0xac, 0xfd, 0x8a, 0xfe, 0x51, 0x6f, 0xfd, 0xb2, 0x70, 0x1c, 0xd7, 0x55, 0x03, 0xeb,
	0x6d, 0xcf, 0x9d, 0x7b, 0xcf, 0x99, 0x33, 0xe7, 0x2e, 0x1a, 0xa3, 0x84, 0xf1, 0xd7, 0xb1, 0x48,
	0xe8, 0x24, 0x55, 0x99, 0x8a, 0x6e, 0xe0, 0xdd, 0x0b, 0xf9, 0x12, 0xf3, 0xb7, 0x29, 0xd7, 0x19,
	0xd9, 0x43, 0x55, 0x73, 0xc9, 0x78, 0x1a, 0x38, 0x6d, 0xe7, 0xb8, 0x16, 0x5b, 0x44, 0xda, 0xf0,
	0x18, 0xd7, 0x99, 0x90, 0x49, 0x26, 0x94, 0x0c, 0x4a, 0xe6, 0xb0, 0x58, 0x8a, 0x4e, 0xe1, 0xcf,
	0x89, 0xf4, 0x44, 0x49, 0xcd, 0x49, 0x08, 0x37, 0xb5, 0xdf, 0x96, 0x2b, 0xc7, 0xd1, 0x25, 0xfc,
	0x87, 0x4c, 0xa5, 0x7c, 0x9b, 0xea, 0x2e, 0x2a, 0xef, 0xc9, 0x78, 0xca, 0x8d, 0x9e, 0x1f, 0xcf,
	0x41, 0xd4, 0x41, 0xdd, 0x4e, 0x5b, 0x29, 0x82, 0xf2, 0x30, 0xd1, 0x43, 0x3b, 0x6c, 0xbe, 0xa3,
	0x0f, 0x07, 0x3b, 0xd7, 0x42, 0xb2, 0x3b, 0xc5, 0xb6, 0xca, 0xf4, 0x51, 0x95, 0x8a, 0xf1, 0x01,
	0x33, 0x3a, 0x5e, 0x6f, 0x9f, 0xae, 0x4d, 0xd2, 0x5b, 0xfb, 0x68, 0x83, 0xab, 0xd8, 0xb6, 0x86,
	0x5d, 0x60, 0x59, 0x25, 0x87, 0xc0, 0x28, 0x47, 0x86, 0xde, 0x8f, 0x0b, 0x95, 0xe8, 0xcb, 0x41,
	0x73, 0x49, 0x6a, 0xef, 0xdd, 0x45, 0x49, 0x30, 0xd3, 0xec, 0xf5, 0x0e, 0xe8, 0xfa, 0x71, 0x51,
	0xb4, 0x24, 0x18, 0x09, 0xf0, 0x3f, 0x61, 0x2c, 0xe5, 0x5a, 0xdb, 0xe7, 0x5f, 0x40, 0x72, 0x01,
	0x97, 0x09, 0x9d, 0x25, 0xf2, 0x99, 0x07, 0xff, 0x7e, 0xc1, 0x96, 0x77, 0xff, 0xd1, 0xc4, 0x09,
	0x5a, 0x33, 0xda, 0xc7, 0x59, 0x0a, 0xb9, 0x89, 0x3c, 0x23, 0xa7, 0x90, 0x51, 0xef, 0xd3, 0x81,
	0xbb, 0x60, 0x26, 0x1d, 0x94, 0x67, 0xab, 0x41, 0x7c, 0x5a, 0x58, 0xb5, 0xb0, 0x4e, 0x57, 0xf6,
	0xe5, 0x08, 0x15, 0x93, 0x2a, 0xa9, 0xd3, 0xe2, 0x6e, 0x84, 0x0d, 0xba, 0x1a, 0xf6, 0x19, 0xdc,
	0x85, 0x37, 0xd2, 0x5c, 0x0f, 0x2a, 0x6c, 0x6d, 0x18, 0x27, 0xe7, 0xa8, 0xe5, 0xb7, 0xfe, 0x61,
	0x82, 0xd0, 0x0d, 0x4f, 0x4f, 0x55, 0xf3, 0x6f, 0xf4, 0xbf, 0x03, 0x00, 0x00, 0xff, 0xff, 0x46,
	0xeb, 0xe4, 0x5e, 0x2d, 0x03, 0x00, 0x00,
}
