// Code generated by protoc-gen-go. DO NOT EDIT.
// source: kademlia.proto

/*
Package kademlia is a generated protocol buffer package.

It is generated from these files:
	kademlia.proto

It has these top-level messages:
	PingRequest
	PingResponse
	StoreRequest
	StoreResponse
*/
package kademlia

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PingRequest struct {
	Sender      string `protobuf:"bytes,1,opt,name=sender" json:"sender,omitempty"`
	Destination string `protobuf:"bytes,2,opt,name=destination" json:"destination,omitempty"`
}

func (m *PingRequest) Reset()                    { *m = PingRequest{} }
func (m *PingRequest) String() string            { return proto.CompactTextString(m) }
func (*PingRequest) ProtoMessage()               {}
func (*PingRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *PingRequest) GetSender() string {
	if m != nil {
		return m.Sender
	}
	return ""
}

func (m *PingRequest) GetDestination() string {
	if m != nil {
		return m.Destination
	}
	return ""
}

type PingResponse struct {
	Response string `protobuf:"bytes,1,opt,name=response" json:"response,omitempty"`
}

func (m *PingResponse) Reset()                    { *m = PingResponse{} }
func (m *PingResponse) String() string            { return proto.CompactTextString(m) }
func (*PingResponse) ProtoMessage()               {}
func (*PingResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *PingResponse) GetResponse() string {
	if m != nil {
		return m.Response
	}
	return ""
}

type StoreRequest struct {
	Sender string `protobuf:"bytes,1,opt,name=sender" json:"sender,omitempty"`
	Value  string `protobuf:"bytes,2,opt,name=value" json:"value,omitempty"`
}

func (m *StoreRequest) Reset()                    { *m = StoreRequest{} }
func (m *StoreRequest) String() string            { return proto.CompactTextString(m) }
func (*StoreRequest) ProtoMessage()               {}
func (*StoreRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *StoreRequest) GetSender() string {
	if m != nil {
		return m.Sender
	}
	return ""
}

func (m *StoreRequest) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type StoreResponse struct {
	Hash string `protobuf:"bytes,1,opt,name=hash" json:"hash,omitempty"`
}

func (m *StoreResponse) Reset()                    { *m = StoreResponse{} }
func (m *StoreResponse) String() string            { return proto.CompactTextString(m) }
func (*StoreResponse) ProtoMessage()               {}
func (*StoreResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *StoreResponse) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

func init() {
	proto.RegisterType((*PingRequest)(nil), "PingRequest")
	proto.RegisterType((*PingResponse)(nil), "PingResponse")
	proto.RegisterType((*StoreRequest)(nil), "StoreRequest")
	proto.RegisterType((*StoreResponse)(nil), "StoreResponse")
}

func init() { proto.RegisterFile("kademlia.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 205 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcb, 0x4e, 0x4c, 0x49,
	0xcd, 0xcd, 0xc9, 0x4c, 0xd4, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57, 0x72, 0xe7, 0xe2, 0x0e, 0xc8,
	0xcc, 0x4b, 0x0f, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0x11, 0x12, 0xe3, 0x62, 0x2b, 0x4e, 0xcd,
	0x4b, 0x49, 0x2d, 0x92, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x82, 0xf2, 0x84, 0x14, 0xb8, 0xb8,
	0x53, 0x52, 0x8b, 0x4b, 0x32, 0xf3, 0x12, 0x4b, 0x32, 0xf3, 0xf3, 0x24, 0x98, 0xc0, 0x92, 0xc8,
	0x42, 0x4a, 0x5a, 0x5c, 0x3c, 0x10, 0x83, 0x8a, 0x0b, 0xf2, 0xf3, 0x8a, 0x53, 0x85, 0xa4, 0xb8,
	0x38, 0x8a, 0xa0, 0x6c, 0xa8, 0x59, 0x70, 0xbe, 0x92, 0x0d, 0x17, 0x4f, 0x70, 0x49, 0x7e, 0x51,
	0x2a, 0x21, 0x5b, 0x45, 0xb8, 0x58, 0xcb, 0x12, 0x73, 0x4a, 0x53, 0xa1, 0xf6, 0x41, 0x38, 0x4a,
	0xca, 0x5c, 0xbc, 0x50, 0xdd, 0x50, 0xab, 0x84, 0xb8, 0x58, 0x32, 0x12, 0x8b, 0x33, 0xa0, 0x9a,
	0xc1, 0x6c, 0xa3, 0x70, 0x2e, 0x0e, 0x6f, 0xa8, 0x4f, 0x85, 0x94, 0xb9, 0x58, 0x40, 0x4e, 0x13,
	0xe2, 0xd1, 0x43, 0xf2, 0xaa, 0x14, 0xaf, 0x1e, 0x8a, 0x7b, 0xd5, 0xb8, 0x58, 0xc1, 0xa6, 0x0a,
	0xf1, 0xea, 0x21, 0xbb, 0x4d, 0x8a, 0x4f, 0x0f, 0xc5, 0xb2, 0x24, 0x36, 0x70, 0xb8, 0x19, 0x03,
	0x02, 0x00, 0x00, 0xff, 0xff, 0xbd, 0xe0, 0xd9, 0x0c, 0x49, 0x01, 0x00, 0x00,
}
